import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "./components/Navbar";
import { auth } from "../lib/auth";
import { headers } from "next/headers";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Temu App Tutorial",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({ headers: await headers() });
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} bg-gradient-to-t from-amber-100 via-gray-100 to-orange-50`}
      >
        <Navbar session={session} />
        <div className=" flex flex-col gap-10 ml-10 mr-10 ">
          {children}
          </div>

        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
